### ISSUE TITLE
didn't see any part of the code dealing with/preprocessing the whole slide image

### ISSUE THREAD

**Issue by jiajundeng** [jlevy44/PathFlow-MixMatch#21]
I didn't see any part of the code dealing with/preprocessing the whole slide image. Did I misunderstand something? Hope you can give me some tips, Thanks in advance!

**Comment by sumanthratna** [comment]
@jlevy44 might be able to provide some more insight but perhaps you can try writing your own preprocessing script and writing your preprocessed WSIs to files. Then, just run MixMatch on those output files instead of the originals. 

It's not a perfect solution, since you might end up running low on file storage but I think it should be a feasible workaround. I hope that works for you!

**Comment by jlevy44** [comment]
Preprocessing is not a part of this pipeline, but as long as you can supply the file in the valid image format, it should be able to run. Utilizing other preprocessing workflows that prepare the images in such a format could improve results. I will note that we are refactoring the repository, those changes are still in the works and we do have an experimental branch that we are finetuning.

**Comment by jiajundeng** [comment]
Thanks for your quick reply!
